# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 80ef941b57c7f8f3ca10bc3b3cb95669d7ea4a69ef3d7f509665aec80ff7eab6f064e4b396127a7c663456cc21be2b1d81f4a2c98689aabe4a077e3ac9c62249

test:
  secret_key_base: 74516b77a22b0bda598676c9e8fc97e37b321799a11ddfde9791f24b00109314ce89839b33948e0fcf9585f0b2812999912b767b5f77fbf9d5407fa5313b6378

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
