# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e732304302923bf04f2ef5ce9c2cf53d6517e57076c197c2dc987d629f28fb14273b6803abe59a452da10ac49f0c476173c53669719b6379b0af78c0ad2d6737

test:
  secret_key_base: 3cbd9d4a738a6c80a888aae91bc13a0a3349202cabcc5e2d92b1ba787a6e10aec0a514ce80b7aae6bb60406c5673b65e9027a66b66d23721a8d054c505fa1deb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
